### ISSUE TITLE
HTML to Markdown

### ISSUE THREAD

**Issue by ThomasTJdev** [soasme/nim-markdown#1]
Any plans on reversing from HTML => Markdown?

**Comment by soasme** [comment]
Thank you for bringing this proposal. My answer is it's possible but not in a short term. Currently, I think the goal is to make Markdown => HTML feature complete and stable.

**Comment by soasme** [comment]
Close the issue since I have put the task in the roadmap in `README.md` though the least priority. Will reference future pull request to this one when getting started. Thanks again! 👍
