### ISSUE TITLE
add list of working / not yet working markdown features in nim-markdown

### ISSUE THREAD

**Issue by timotheecour** [soasme/nim-markdown#2]
* could you add a list of working / not yet working markdown features in nim-markdown?
maybe as a list of checkboxes kept in sync with code changes eg:

- [ ] image links
- [x] url links

this could be in README.md or another file status.md

* I'm curious whether nim-markdown can already be used to process (a subset of) markdown files in Nim repo, if we were to start replacing some rst files with markdown, see https://github.com/nim-lang/Nim/issues/9291#issuecomment-431705555

* what would you suggest for this question:
https://github.com/nim-lang/Nim/issues/9291#issuecomment-428877292
```
How do I write

`term`:idx:
in markdown?
```

**Comment by soasme** [comment]
1. I've put the feature list in the readme.
2. The short answer is yes, considering I've implemented almost all essential features.
3. Re the suggestion, is the given text converted to `<code class="idx">term</code>` or something like that? If so, in the current version, you can use inline HTML:

```nim
markdown("<code class="idx">term</code>", "KeepHTML: true")
```

^ Especially for 3, it's possible to add a parsing rule for it. However, it's not a traditional Markdown syntax. I would like more to implement it as a 3party plugin. I just used Nim for over one week but I'll explore how to do it. Appreciate any help. :)

**Comment by kaushalmodi** [comment]
> I just used Nim for over one week 

Wow! It's great to see what you did in a week! Keep going!

**Comment by soasme** [comment]
Close the issue. Features and roadmaps are documented in README.
