### ISSUE TITLE
How to produce AST?

### ISSUE THREAD

**Issue by Benjamin-Lee** [soasme/nim-markdown#45]
I've been reading through the docs and am lost trying to produce the AST described in the docs:

```
Document()
+-Heading(level=1)
  +-Text("H")
  +-Text("e")
  +-Text("l")
  +-Text("l")
  +-Text("o")
  ...
+-Paragraph()
  +-Text("W")
  +-Text("e")
  ...
  +-Em()
    +-Text("n")
    +-Text("i")
    +-Text("m")
    ...
  +-Text(".")
  ...
```

Given a string, such as `# Hello World\This is a **bold** word.`, how would I go about generating that object? If possible, can that be more explicitly explained in the docs? This project looks to be exactly what I need so I would really appreciate the help.

**Comment by soasme** [comment]
@Benjamin-Lee Does the doc [Advanced Usages: Operate AST](https://github.com/soasme/nim-markdown/blob/master/docs/advance_usages.md#operate-ast) help? Basically, you can assign an additional parameter `root`, which is the root AST node you're looking for.

**Comment by Benjamin-Lee** [comment]
That’s exactly what I was looking for — I completely missed it. Thanks!
