### ISSUE TITLE
Consider making `config` more strict/strongly-typed

### ISSUE THREAD

**Issue by haltcase** [soasme/nim-markdown#5]
## problem

The `config` parameter to `markdown()` is currently a regex-parsed string that's prone to both user & dev error, can blow up at runtime rather than compile time, and isn't great for documentation or autocomplete. TLDR it's "stringly typed" and that's not ideal.

https://github.com/soasme/nim-markdown/blob/9348402d601a7a284e8e3da4137293d79cf201e7/src/markdown.nim#L865-L868

## solution

If the parameters are all flags (and they currently are) then it's probably best to use a `set[enum]` instead. This is a pattern I've used pretty often:

```nim
type
  MarkdownOption* {.pure.} = enum
    Escape, KeepHtml

  MarkdownOptions* = set[MarkdownOption]

const
  defaultMarkdownOptions* = {Escape}

proc markdown* (doc: string, config = defaultMarkdownOptions): string
```

This way if a user typos and passes `Escaep` they'll get a compile time error, or might even avoid it entirely because of code suggestions. If you want to go this route I'm willing to make a PR.

### alternative

If future options might be non-boolean they wouldn't be covered by this and maybe something like an object + proc combo would be needed:

```nim
type
  MarkdownConfig* = object
    escape, keepHtml: bool
    someConfigurableString: string

proc initMarkdownConfig* (
  escape = true,
  keepHtml = false,
  someConfigurableString = ""
): MarkdownConfig
```

It's a bit heavier and more verbose though.

**Comment by soasme** [comment]
@citycide Nice proposal. Due to below potential cases, the config might not contain only the bool option. 

* customize indent(int),
* customize footnote class(string),
* ...

I would prefer the alternative solution. In addition, we can provide two APIs for the end users:

```nim
# We can hide MarkdownConfig concept when the users may just want to overwrite one or two options.
proc markdown(
  text: string,
  escape: bool = true,
  keepHTML: bool = true,
  more: string = ""
): string;

# For those want to deeply customize the behaviour, they can use this API.
proc markdown(text: string, config: MarkdownConfig): string;
```

**Comment by haltcase** [comment]
Hmm. Not sure about keeping a proc with that signature since that definition is going to become huge as options are added and the two will have to be kept in sync. I think `config` should have sane defaults and if users need to override they should use `initMarkdownConfig(...)`.
