### ISSUE TITLE
API docs missing?

### ISSUE THREAD

**Issue by pietroppeter** [soasme/nim-markdown#59]
Hi, I am not able to find a working link to API docs (which I see they are commited in the repo at https://github.com/soasme/nim-markdown/tree/master/docs/htmldocs). Currently the link I find is https://www.soasme.com/nim-markdown/ which does not contain API documentation.

**Comment by soasme** [comment]
I think it's missing `index.html`, but all the others are okay:

https://www.soasme.com/nim-markdown/htmldocs/markdown.html
https://www.soasme.com/nim-markdown/htmldocs/theindex.html

**Comment by pietroppeter** [comment]
ok, good, so it is just a matter of discoverability from github repo. created a PR with the correct links
