### ISSUE TITLE
Exported `toSeq` in this package robbed me of 3 hours of my life

### ISSUE THREAD

**Issue by cmd410** [soasme/nim-markdown#62]
https://github.com/soasme/nim-markdown/blob/a661c260795cbdbb02fc73b52b3aa8b6b78bfb08/src/markdown.nim#L470

Please, don't export `toSeq` proc. I've wasted a lot of time debugging why my `toSeq` wasn't working.
It turns out, it's due to this issue: https://github.com/nim-lang/RFCs/issues/512

I've found a somewhat dirty trick to ease the pain
```nim
import markdown except toSeq
```
Which is fine, but would be better if wasn't exported in the first place. Is there any particular reason for this `toSeq` to be exposed?

**Comment by soasme** [comment]
@cmd410 I'll patch the code and make a new release shortly. Thank you for reporting the issue.
