### ISSUE TITLE
support extension `escaped_line_breaks`

### ISSUE THREAD

**Issue by timotheecour** [soasme/nim-markdown#8]
full context: https://github.com/nim-lang/Nim/issues/9291#issuecomment-432351178
it's useful for editors that automatically trim trailing spaces

**Comment by soasme** [comment]
Will support it in the next version.

**Comment by GULPF** [comment]
[Note that this is part of the GFM spec](https://github.github.com/gfm/#hard-line-breaks)

**Comment by soasme** [comment]
v0.3.4 released. Nim-markdown now supports hard line breaks by both `\` and trailing whitespaces.

```nim
test "inline break":
  check markdown("hello\nworld") == "<p>hello\nworld</p>"
  check markdown("hello\\\nworld") == "<p>hello<br />\nworld</p>"
  check markdown("hello  \nworld") == "<p>hello<br />\nworld</p>"
```
